### ISSUE TITLE
pytest error "No module named 'pyvirtualdisplay'"

### ISSUE THREAD

**Issue by yfletberliac** [rlberry-py/rlberry#11]
$ pytest

==================================================== test session starts ====================================================
platform darwin -- Python 3.7.9, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /Users/yannisfletberliac/Developer/rlberry-py/rlberry
collected 162 items / 1 error / 161 selected

========================================================== ERRORS ===========================================================
___________________________ ERROR collecting rlberry/rendering/tests/test_rendering_interface.py ____________________________
ImportError while importing test module '/Users/yannisfletberliac/Developer/rlberry-py/rlberry/rlberry/rendering/tests/test_rendering_interface.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../miniconda3/envs/rlberry/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
rlberry/rendering/tests/test_rendering_interface.py:4: in <module>
    from pyvirtualdisplay import Display
E   ModuleNotFoundError: No module named 'pyvirtualdisplay'
================================================== short test summary info ==================================================
ERROR rlberry/rendering/tests/test_rendering_interface.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================== 1 error in 1.49s ======================================================

**Comment by eleurent** [comment]
`pyvirtualdisplay `is in the `tests_require`: https://github.com/rlberry-py/rlberry/blob/main/setup.py#L24
It should work if you install with `pip install -e .[tests]`?

**Comment by yfletberliac** [comment]
yes! thanks
