### ISSUE TITLE
Minimize star imports

### ISSUE THREAD

**Issue by mmcenta** [rlberry-py/rlberry#121]
We should minimize star imports (that is, using 'from ... import *) because:

1) They reduce code readability (it becomes harder to pinpoint from where an object was imported);

2) They can cause bugs when a star import overrides an object previously imported. These are typically difficult to catch.

3) They are actually discouraged in most styleguides.

_As suggested in https://github.com/rlberry-py/rlberry/pull/110#discussion_r807213843_

**Comment by TimotheeMathieu** [comment]
We can also test for them in the "formating check" that we do at each PR to ensure that we respect this guideline, flake8  (something like F405 that I can include in the check).

**Comment by mmcenta** [comment]
I agree with the formatting check.

I'm assigning myself to this issue and I will submit a PR to correct the style soon!
