### ISSUE TITLE
Naming convention for agents

### ISSUE THREAD

**Issue by omardrwch** [rlberry-py/rlberry#13]
I suggest `VeryCoolAgent` as convention, what do you think?

This would change, for instance:
`PPOAgent` -> `PpoAgent`

`RSUCBVIAgent` -> `RsUcbviAgent`

etc.

**Comment by xuedong** [comment]
I object.

**Comment by xuedong** [comment]
This topic should be based on consensus decision-making.

**Comment by omardrwch** [comment]
I can live with `PPOAgent`, `A3CAgent`, `DQNAgent`

But not  'LSVIUCBAgent', `RSUCBVIAgent` etc.

Maybe we can limit to 4 (or 3 or 5?) the number of consecutive capital letters in the class name.

**Comment by yfletberliac** [comment]
Let's take the example of algorithms whose names are not all-uppercase e.g. ApeX...

With the first convention, we would have ApeXAgent. With the second, ApexAgent.

The second prioritizes uniform library naming (and also PEP8), the first one prioritizes original naming.

**Comment by yfletberliac** [comment]
I have a preference for the second one.

**Comment by omardrwch** [comment]
I agree with Yannis, for uniformity. Aesthetically, I don't have a preference, but I like PEP8 and uniform stuff.

**Comment by yfletberliac** [comment]
But it's really not a strong opinion on my side, I would be ok with either choice. Not a big deal for me.

**Comment by xuedong** [comment]
I think I won, closing the issue.
