### ISSUE TITLE
Bug when creating AgentManagers

### ISSUE THREAD

**Issue by mmcenta** [rlberry-py/rlberry#134]
Hello, I was recently working with the agent checks on `rlberry/utils/check_agent.py` and I was encountering the following error:

>  fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "./examples/demo_examples/demo_sb_agent.py", line 30, in <module>
    stats = AgentManager(
  File "/Users/mmcenta/miniconda3/envs/rlb/lib/python3.8/site-packages/rlberry/manager/agent_manager.py", line 386, in __init__
    self.rlberry_version = get_rlberry_version()
  File "/Users/mmcenta/miniconda3/envs/rlb/lib/python3.8/site-packages/rlberry/utils/hash_utils.py", line 25, in get_rlberry_version
    subprocess.check_output(
  File "/Users/mmcenta/miniconda3/envs/rlb/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/mmcenta/miniconda3/envs/rlb/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.

It is caused by the `get_rlberry_version()` function introduced recently (in PR #126), which requires the current directory (or its parent) to be a  git repository. As it turns out, after installing the library with `pip install .`, this function is called from inside the library (somewhere in `~/miniconda3/envs/rlb/lib/python3.8/site-packages/rlberry/utils`, in my case). The result is the error above because the other directory is not part of a git repository.

### Reproducing

The code below reproduces the bug:

```python
from rlberry.agents.torch import A2CAgent
from rlberry.envs import gym_make
from rlberry.manager import AgentManager

if __name__ == "__main__":
    env_ctor = gym_make
    env_kwargs = {'id': 'CartPole-v0'}
    stats = AgentManager(
        A2CAgent,
        (env_ctor, env_kwargs),
        agent_name="A2C",
        init_kwargs=dict(batch_size=16),
        fit_budget=100,
    )
```

Running this code produces the same error from above. Do NOT run the code from the `rlberry` main directory, because in that case it will import the local code which runs in a git directory. I run this code from a subdirectory `rlberry/test_bug/bug.py`, which forces Python to load the installed version of rlberry.

**Comment by TimotheeMathieu** [comment]
My fault, bug introduced in PR #126. I will look into it.

**Comment by TimotheeMathieu** [comment]
I think the best way to solve this would be to have some `rlberry.__git_commit_hash__ `similarly to the `rlberry.__version__` except that this git commit hash should change every time we do a commit. 

Using a git hook for instance. 
What do you think ? @mmcenta @omardrwch

**Comment by omardrwch** [comment]
I think that the best solution would be to update `rlberry.__version__` according to the last tag and the current commit, as described here: https://stackoverflow.com/a/53891548

**Comment by TimotheeMathieu** [comment]
I don't know, it gives a clean result we agree but it means that each dev has to install versioneer, and every person that wants to contribute to rlberry must install versioneer. Which is not something that can be automatically done with requirements.txt. 
The same problem is in fact also present with hooks. 
Maybe we can use github workflow to solve this ? at each merge into main generate the version ?

**Comment by omardrwch** [comment]
Yes, we can use github actions for that. For now we could just remove the git hash to fix the issue, and we can work on the proper versioning later (unless it's very easy to setup the workflow)

**Comment by mmcenta** [comment]
I actually don't have much experience in versioning - do you know how do other projects solve this issue?
I agree that if setting up versioning takes time we should just push a temporary bugfix first.

**Comment by TimotheeMathieu** [comment]
I think it is not very easy. I will fix it by including the git command into a try except.

From my experience, other projects use the version or the git tag that they update by hand. The advantage of our approach is to have the specific commit hash of the rlberry that spawned the agent_manager. Versioneer would be better and I think we could do a versioneer github action workflow, I will look into it.

**Comment by TimotheeMathieu** [comment]
I solved the bug in PR #136 but it is not verry clean.

By doing research I discovered https://github.com/mtkennerly/dunamai which seems very nice, in particular because it is available as a github action !

**Comment by mmcenta** [comment]
Nice work with the fix so far!

But there is something else bothering me: this bug wasn't detected by our tests. Was there any way to prevent this? I think the `rlberry/tests/test_agent.py` file should have failed if rlberry was loaded from the installed version and not the current repository.

**Comment by TimotheeMathieu** [comment]
The thing is that tests are run from rlberry main directory which is why it was not spotted. 
I actually don't really understand why you had the error because on my PC, with pip install . -e it works, maybe a difference with windows or other ? Anyway I am working on a cleaner solution in the PR. 
I don't think I could do a regression test for this, I would have to run the tests from outside rlberry folder, but pytest automatically runs tests from inside rlberry folder I think.

**Comment by mmcenta** [comment]
It may not be a real bug, now that I look into it. Installing from source with `pip install -e .` actually works but I have no clue why editable mode fixes this.

**Comment by TimotheeMathieu** [comment]
This is now entirely solved. 

The version is now in a static file `rlberry/_version.py` and this file contains `rlberry/__version__` that is automatically recorder in AgentManager and also it is recorded in the doc and setup.py.
The _version.py file is automatically updated by a workflow that activate at each PR merge. This creates a commit that changes the version.  

Typical version is 
`__version__ = "v0.2.1.post82.dev0+feb610b "`

which means v0.2.1 (from the tag) after which we did 82 commits on main branch, the last of which has hash beginning with feb610b. This indicate precisely which version of rlberry was used and because it is in the github workflow, there is no need to change the version locally, so no git dependency on git or anything of the sort.
