### ISSUE TITLE
Bug in plot_writer_data

### ISSUE THREAD

**Issue by omardrwch** [rlberry-py/rlberry#151]
The following code:

```python
from rlberry.agents import UCBVIAgent
from rlberry.envs import GridWorld
from rlberry.manager import AgentManager, plot_writer_data

manager = AgentManager(
    UCBVIAgent,
    (GridWorld, {}),
    fit_budget=10,
    output_dir='rlberry_data/ucbvi_experiment',
    outdir_id_style=None
)
manager.fit()
plot_writer_data(manager, tag='episode_rewards')
```

raises the error:

```
ValueError: input dir not found, verify that the agent are trained and that AgentManager.outdir_id_style="timestamp"
```

Since the agent manager is given to `plot_writer_data`, we should not care about `outdir_id_style`, all we need is already in the manager.

Also, this leads to a completely unexpected behavior if the code above is previously called with `outdir_id_style="timestamp"`, since we'll plot the data from the previous run, instead of data in the current manager.

**Comment by TimotheeMathieu** [comment]
Yes I agree. 
We should have some hierarchy on how to choose the files to plot. If the agentmanager is fitted -> plot these data. If it is not fitted but there are timestamp -> plot last data, if there is no timestamp and is not fitted, warn. 

Or maybe do something interactive in case not fitted and not timestamped, where plot_writer_data asks to select one choice from a list of possible folders ? what do you think ?

**Comment by omardrwch** [comment]
I think that `plot_writer_data(input_obj, ..,)` should behave as follows:

* If `input_obj` is an AgentManager instance (or a list of instances), nothing should be loaded from memory: we plot the data stored in that instance
* If `input_obj` is a string/Path, we load the most recent manager from that path.

**Comment by TimotheeMathieu** [comment]
Ok but If input_obj is a string/Path, we need the timestamps in order to be able to load most recent . 
What do we do if there is no timestamp ?
And also I think it would be nice to select not necessarily the most recent but an older example. Either interactively or by giving the exact path as argument.

**Comment by omardrwch** [comment]
I think we could distinguish two cases when we have a path:

* If `input_obj` is a path to a .pickle file, we load the file as an AgentManager (which should allow us to load older experiments);
* If `input_obj` is a folder, we take the .pickle file in the most recent subfolder (either by looking at the timestamp in the folder name, or by looking at its creation time).

What do you think?

**Comment by TimotheeMathieu** [comment]
Ok for me. I can do it.
