### ISSUE TITLE
Bug with q_net_constructor in DQN

### ISSUE THREAD

**Issue by omardrwch** [rlberry-py/rlberry#155]
I believe an else
```python
else:
    q_net_ctor = q_net_constructor
```
is missing after

https://github.com/rlberry-py/rlberry/blob/8168dfc73a802dc9a6308e16a7d7bdce715d4f17/rlberry/agents/torch/dqn/dqn.py#L153

(creating this issue so that I can double-check later)

**Comment by xuedong** [comment]
hein ?
