### ISSUE TITLE
Use logging for logging

### ISSUE THREAD

**Issue by eleurent** [rlberry-py/rlberry#16]
As this project is likely to involve a substantial amount of code and debugging effort, it would be best to move from `print` statements to the official Python 3 [logging](https://docs.python.org/3/howto/logging.html) module, which provides advanced control over the logs (levels of severity, output to file or console, enable/disable logging of specific modules, etc.)

**Comment by omardrwch** [comment]
I see the usefulness of this logging module, but I don't think it should replace all `print` statements. 

I think we can keep the `verbose` convention for the agents for printing progress messages (as in the README), as they do in sklearn ([example](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/neural_network/_multilayer_perceptron.py)), and use `logging` for information that is useful for debug. Maybe that's what you meant.

**Comment by eleurent** [comment]
That's not what I meant: the logging package is already a comprehensive way to handle different levels of verbosity. You can also have different levels for different outputs (e.g only info in console and up to debug in a log file)

Having a verbose flag is redundant IMO. I find logging superior to print+verbose flags, but I'd rather have one consistent solution than a mix of both.

**Comment by omardrwch** [comment]
Ok, I like this full-logging solution too, it seems better to avoid passing a verbose flag to each agent.
