### ISSUE TITLE
Error when stable baselines is not installed

### ISSUE THREAD

**Issue by omardrwch** [rlberry-py/rlberry#166]
Trying to use `rlberry.agents` raises an error if stable baselines is not installed due to this line:

https://github.com/rlberry-py/rlberry/blob/731879e986f155b13782ddc54c462515f374b774/rlberry/agents/__init__.py#L18

We could include a check before this line.

**Comment by mmcenta** [comment]
Should we also produce a warning when it is not loaded?

**Comment by TimotheeMathieu** [comment]
We can do a warning or we can avoid this by not putting it in the init. We say that people must import from `rlberry.agents.stable_baselines.SableBaselineAgent`. Kind of like when we say that we import from `rlberry.agents.torch.a2c` and not `rlberry.agents.a2c`.

**Comment by mmcenta** [comment]
> We can do a warning or we can avoid this by not putting it in the init. We say that people must import from `rlberry.agents.stable_baselines.SableBaselineAgent`. Kind of like when we say that we import from `rlberry.agents.torch.a2c` and not `rlberry.agents.a2c`.

Ops, I made the PR before seeing this comment.

**Comment by omardrwch** [comment]
I think requiring an import from rlberry.agents.stable_baselines.SableBaselineAgent is better than the warning. A warning in the init file would appear everytime we use any agent, even when we don't need the ones from stable baselines

**Comment by mmcenta** [comment]
No problem, I think it's a fine solution too.

I can just delete the import from `__init__.py` (and the logger) in my PR if that's okay.
