### ISSUE TITLE
Attributes docstrings

### ISSUE THREAD

**Issue by TimotheeMathieu** [rlberry-py/rlberry#188]
For now there is practically no attribute documentation except in Agent and AgentWithSimplePolicy. It would be nice to have this for every agent. and every environment also.

**Comment by KohlerHECTOR** [comment]
To do torch: A2C-MDQN.
To do non-torch: all of them.

**Comment by riccardodv** [comment]
So far, we have put all attributes. These are often just a copy and paste of the parameters, leading to some redundancy. I understand it could be helpful to have both things, but do you think this is the best way to do it? The docstring will be quite long in this way.

**Comment by TimotheeMathieu** [comment]
Maybe it would be sufficient to document the attributes that are not arguments but created during the fit. A bit like in scikit-learn ;) . in the case of scikit-learn, the attributes that could be reused by the user are denoted with a "_" at the end (e.g. regressor.coef_ ) they say "an attribute that have a meaningful value after fit() was called". Maybe we  could take the same convention for rlberry agents ?
