### ISSUE TITLE
The loggs are not printed anymore on screen

### ISSUE THREAD

**Issue by riccardodv** [rlberry-py/rlberry#195]
Hello! I have the impression that something changed with our library very recently and now at least DQN and A2C do not print loggs anymore on screen (I suspect all the others as well). This is a bit annoying because you have the feeling it is not working while instead simply it is not printing anything. I suspect it has to do with `add_scalar()` but I haven't been able to understand what changed. Do you know what could be the problem?

**Comment by omardrwch** [comment]
I also noticed that! The DefaultWriter has been updated recently, maybe there was some change breaking the logs.

**Comment by omardrwch** [comment]
Here https://github.com/rlberry-py/rlberry/blob/082846877971ff3880b8cfee32d9d87efb5c20e7/rlberry/utils/writers.py#L179

```python
        if not self._log_time:
            self._log()
```
`self._log_time` is always True, and `_log()` is not called

**Comment by TimotheeMathieu** [comment]
Solved by PR #196
