### ISSUE TITLE
What is the purpose of the Getting started section in README?

### ISSUE THREAD

**Issue by yfletberliac** [rlberry-py/rlberry#24]
In the README, the Getting started [section](https://github.com/rlberry-py/rlberry#getting-started) only covers the Tests. Shouldn't we include a link to the [tutorials](https://github.com/rlberry-py/tutorials)?

**Comment by omardrwch** [comment]
It's a good idea to put a link to the tutorials. We also have the `examples/` folder, which is messy, but I wanted to make the examples in google colab, and put links in the README to the most interesting examples/notebooks. What do you think?

**Comment by xuedong** [comment]
The getting started section is still under construction

**Comment by eleurent** [comment]
@omardrwch  I agree: we should have colab notebooks rather than python scripts, and redirect to them (in a structured way) in the getting started section of the doc.
