### ISSUE TITLE
Need a standard for docstring writing

### ISSUE THREAD

**Issue by xuedong** [rlberry-py/rlberry#27]
It's pretty a mess for the moment... And probably write it down in the CONTRIBUTING guide.

**Comment by omardrwch** [comment]
When we started writing the library, I asked you about that, and we agreed to use the numpy style for the docstring (https://numpydoc.readthedocs.io/en/latest/format.html).

**Comment by eleurent** [comment]
This should be mentioned in the contributing guide.
+ PyCharm can be configured to use numpy style in Settings | Tools | Python Integrated Tools | Docstring format | Numpy

**Comment by eleurent** [comment]
But I think that the default reStructuredText syntax has the advantage of being used by Sphinx/ReadTheDocs.
I don't know whether sphinx can be configured for other docstring styles.

**Comment by omardrwch** [comment]
Maybe this solves the problem with sphinx: https://github.com/numpy/numpydoc
