### ISSUE TITLE
Hyperparameter optim samplers

### ISSUE THREAD

**Issue by xuedong** [rlberry-py/rlberry#29]
**Is your feature request related to a problem? Please describe.**
Why only 'random' and 'optuna_dafault' are supported? I don't understand, is there any additional technical difficulties to include other samplers?

**Describe the solution you'd like**
All Optuna samplers being supported.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by omardrwch** [comment]
No technical difficulty, we just need more if statements, and see how to handle the parameters of each sampler. 
Same for other pruning methods.
