### ISSUE TITLE
Weird error handling in replay buffer

### ISSUE THREAD

**Issue by TimotheeMathieu** [rlberry-py/rlberry#301]
We encountered a weird error during MDQN tests:

```
[ERROR] 08:26: Cannot sample from ReplayBuffer if the number of stored transitions is smaller than chunk_size.chunk_size, returning NoneCurrent replay size = 6, requested chunk_size = 8 
```

This is from https://github.com/rlberry-py/rlberry/blob/237669aff316dbfb939a0b248886bc9116ae0bcb/rlberry/agents/utils/replay.py#L326-L332

If this is really an error, this should raise a RuntimeError or whatever to stop the process. Otherwise, this should be a warning.

**Comment by omardrwch** [comment]
I was following the convention that if the replay cannot be sampled from, it returns `batch=None` (similar to [reverb](https://github.com/deepmind/reverb) if I remember correctly).

When sampling from the replay, the agents should check whether the batch is not None before using it. I think it's better than raising an exception, so I suggest we raise a warning.
