### ISSUE TITLE
Please use the same naming convention for branches

### ISSUE THREAD

**Issue by xuedong** [rlberry-py/rlberry#31]
See the title. I would suggest using hyphen, e.g. feature-hpo, dev-dqn, etc.

**Comment by eleurent** [comment]
I agree that hyphen is better, i used underscore to mimic the syntax of an existing branch (now deleted)

**Comment by yfletberliac** [comment]
I'm not sure it should be in the contributing guidelines - I'm afraid this would be an excessive constraint.

I mean, the name will be appearing under "branches" in the main repo only for internal contributors (us). But external contributors will just fork the repo, then create a branch that will appear on their own fork of the repo. Then they will create a PR and the name of the branch will not impact `rlberry`.
