### ISSUE TITLE
American English or British English?

### ISSUE THREAD

**Issue by yfletberliac** [rlberry-py/rlberry#34]
In the README (and maybe in the codebase), there are occurrences of "optimisation" (e.g. in diagram and text) and "optimization" (in text). Also, "visualisation".

We should pick one for the whole repo and stick to it. I usually use American English in papers (optimization, visualization, generalization) so I would vote for `American English`. What do you prefer?

**Comment by omardrwch** [comment]
I vote for American English (also because I'd be lazy to change some functions as `optimize_hyperparams` in `AgentStats`.

**Comment by xuedong** [comment]
ok
