### ISSUE TITLE
evaluate_agents do more evaluation than 'n_simulation' param

### ISSUE THREAD

**Issue by JulienT01** [rlberry-py/rlberry#374]
evaluate_agents on ExperimentManager do more evaluation than the n_simulation  (for PPO)

the n_simulation parameter go to eval_agents() in ExperimentManager, but not to eval() in Agent :  kwarg parameter don't have the n_simulation anymore.
So the eval() is done 10 times (default value)

We need to add n_simulation=1 in the eval_kwargs for the line (experiment_manager.py)
"values.append(agent.eval(**eval_kwargs))"

**Comment by BorisHamadej** [comment]
HI! Is this issue still open? Can I give it a try?

**Comment by JulienT01** [comment]
Yes it's still open, you can do it if you want.

**Comment by TimotheeMathieu** [comment]
Solved, closing.
