### ISSUE TITLE
Seeding, torch and multiprocess in user guide.

### ISSUE THREAD

**Issue by TimotheeMathieu** [rlberry-py/rlberry#465]
Add explanations in the user guide about why we want seeding in rlberry, and how to see torch in the user guide. And reseed torch in the init of ExperimentManager.

**Comment by JulienT01** [comment]
Shoud be donne here : https://github.com/rlberry-py/rlberry/pull/463
Waiting for code review.

(and the torch reseed, is done in the `_fit_worker` from experiment_manager.py )
