### ISSUE TITLE
Seeding adastop smartly

### ISSUE THREAD

**Issue by TimotheeMathieu** [rlberry-py/rlberry#466]
Adastop do not reuse the seed of the experiment manager. Have a warning if user put a seed in expmanager args.

**Comment by JulienT01** [comment]
Should be ok now:
https://github.com/rlberry-py/rlberry/pull/463

commit : https://github.com/rlberry-py/rlberry/pull/463/commits/cff635a1f15ab957a4209b7b71b9502ad63c7c8a
