### ISSUE TITLE
setup.py does not install some rlberry packages

### ISSUE THREAD

**Issue by omardrwch** [rlberry-py/rlberry#49]
In `setup.py`, we have:

```python
from setuptools import setup, find_packages
packages = find_packages(exclude=['docs', 'notebooks', 'assets'])
```

and some packages are missing from the list. 

For instance, when installing from pip (`pip install 'rlberry[full]==0.1'`) and running

```python
from rlberry.agents.torch.reinforce import REINFORCEAgent
```

we receive the error  `ModuleNotFoundError: No module named 'rlberry.agents.torch.utils' `

**Comment by yfletberliac** [comment]
Did you use `pip install 'rlberry[full]==0.1'` or `pip install -e .[full]`?
(I cannot reproduce the issue)

**Comment by omardrwch** [comment]
I used `!pip install 'rlberry[full]==0.1'`

Here is a notebook reproducing the issue:

https://colab.research.google.com/drive/181kE5N4qzZbiUrEBKV-zJfBOI3Ki2cOE?usp=sharing

**Comment by omardrwch** [comment]
This should be fixed by including the missing `__init__.py` file, done here: 3ec6121ddb689867a068f7b9e2bac6770c2660e8
