### ISSUE TITLE
NameError: name 'torch' is not defined

### ISSUE THREAD

**Issue by szrlee** [rlberry-py/rlberry#54]
**Describe the bug**
Use `pip install -e .[test]` to install the rlberry will not have pytorch installed.
Then if running `python examples/demo_ucbvi_and_opqtl.py`, you will get an error
```python
  File "/xxx/rlberry/rlberry/exploration_tools/typing.py", line 48, in process_type
    elif isinstance(arg, torch.Tensor):
NameError: name 'torch' is not defined
```

**To Reproduce**
```zsh
pip install -e .[test]
python examples/demo_ucbvi_and_opqtl.py
```

**Expected behavior**
Run successfully even without PyTorch because this is a tabular algorithm for a tabular environment.

**Desktop (please complete the following information):**
	-   OS: MacOS
	-   Version  11.5.2
	-   Python version 3.7.11
	-   PyTorch version N/A

**Comment by omardrwch** [comment]
Thanks for catching that! It should be fixed now (commit 6d874c34e2e763e30dfebe3eb89380a5ba4f01bd).

The example is running now, but to run `pytest`, we still need PyTorch to be installed.  

At some point we'll organize better the different installation modes in `setup.py`. If possible,  we recommend a full installation `pip install -e .[full]`  for now.
