### ISSUE TITLE
PyOpenGL in macOS

### ISSUE THREAD

**Issue by omardrwch** [rlberry-py/rlberry#63]
Some rlberry environments use OpenGL for rendering, which might fail in macOS. 

See https://stackoverflow.com/questions/63475461/unable-to-import-opengl-gl-in-python-on-macos for a possible fix.

**Comment by yfletberliac** [comment]
Looks like it would be solved with Python 3.8 instead of 3.7

**Comment by omardrwch** [comment]
If it works, let's go to 3.8 then!
