### ISSUE TITLE
Potential issue with numba installation under macOS

### ISSUE THREAD

**Issue by xuedong** [rlberry-py/rlberry#7]
I am under macOS 10.13 High Sierra, and I encountered the following issue on numba when installing rlberry:

<img width="1280" alt="Screen Shot 2020-11-17 at 13 03 43" src="https://user-images.githubusercontent.com/1488899/99390491-01e91980-28d9-11eb-9067-89a8679905ea.png">

Not sure if it is an issue related to mac or not.

**Comment by xuedong** [comment]
Todo: probably make numba optional

**Comment by yfletberliac** [comment]
Maybe try that? https://stackoverflow.com/questions/36385785/error-installing-numba-on-os-x

**Comment by omardrwch** [comment]
Numba is now optional
